[package]
name = "roost"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
gimli = "0.31.0"
memmap2 = "0.9.4"
nix = { version = "0.29.0", features = ["process", "mman"] }
object = "0.36.4"
timing_rdtsc = "0.1.2"
