name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    container: gcc:13
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Use cmake
        run: cmake --version

      - name: Install OpenGL, glfw3 & libdwarf
        run:
          sudo sapt-get update
          sudo sapt-get install libglfw3-dev 
          sudo sapt-get install libgl1-mesa-dev libglfw3-dev
          sudo apt install libdwarf-dev
      
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
