name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCC 13
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        apt-get update -y
        apt-get install libglfw3-dev -y
        apt-get install libgl1-mesa-dev libglfw3-dev -y
        apt install libdwarf-dev -y
        apt-get install gcc-13 g++-13 -y
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60

    - name: Install CMake
      run: apt-get install cmake -y

    - name: Run build script
      run: ./build.sh
