name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    container: gcc-cmake:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
