name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    container: gcc:13
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Use cmake
        run: cmake --version

      - name: Install OpenGL & glfw3
        run: sudo apt-get update
        run: sudo apt-get install libglfw3-dev
        run: sudo apt-get install libgl1-mesa-dev libglfw3-dev
      
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
