name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19

    - name: OpenGL, GLFW3 & elfutils (libdw)
      run: |
        apt-get update -y
        apt-get install -y libglfw3-dev elfutils libdw-dev libgl1-mesa-dev

    - name: Install CMake
      run: apt-get install cmake -y
    
    - name: Verify version (Debugging)
      run: |
        clang-19 --version
        cmake --version

    - name: Run build script
      run: 
        ./build.sh