name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcc:13
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: OpenGL, GLFW3 & elfutils (libdw)
      run: |
        apt-get update -y
        apt-get install -y libglfw3-dev elfutils libdw-dev libgl1-mesa-dev

    - name: Install CMake
      run: apt-get install cmake -y
    
    - name: Verify version (Debugging)
      run: |
        gcc --version
        cmake --version

    - name: Run build script
      run: 
        ./build.sh