name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    container: gcc:13
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Use cmake
        run: cmake --version

      - name: Install OpenGL, glfw3 & libdwarf
        run: |
          apt-get update
          apt-get install libglfw3-dev -y
          apt-get install libgl1-mesa-dev libglfw3-dev -y
          apt install libdwarf-dev -y
      
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
